src/views/auth_view.py
from flask import Blueprint, render_template, redirect, url_for, request
from models.client_error import ValidationError, AuthError
from models.role_model import RoleModel
from facades.user_facade import UserFacade

auth_blueprint = Blueprint("auth_view", __name__)

@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():
    try:
        if request.method == "GET":
            error = request.args.get('error')
            return render_template("register.html", error = error , user={}, active = "register", admin_role = RoleModel.Admin.value, user_role = RoleModel.User.value)
        
        with UserFacade() as auth_facade:
            auth_facade.user_sign_up()

        return redirect(url_for("auth_view.login"))
    
    except ValidationError as err:
        return render_template("register.html", error = err.message, user = err.model, active = "register", admin_role = RoleModel.Admin.value, user_role = RoleModel.User.value) 

@auth_blueprint.route("/login", methods=["GET", "POST"])
def login():
    try:
        if request.method == "GET":
            error = request.args.get('error')
            return render_template("login.html",error = error, credentials = {}, active = "login", admin_role = RoleModel.Admin.value, user_role = RoleModel.User.value)
        
        with UserFacade() as auth_facade:
            auth_facade.user_log_in()

        return redirect(url_for("home_view.home"))
    
    except (ValidationError, AuthError) as err: 
        return render_template("login.html", error = err.message, credentials = err.model, active = "login", admin_role = RoleModel.Admin.value, user_role = RoleModel.User.value)
    
@auth_blueprint.route("/logout")
def logout():

    with UserFacade() as auth_facade:
        auth_facade.user_log_out()

    return redirect(url_for("home_view.home"))

src/views/home_view.py
from flask import Blueprint, render_template
from models.role_model import RoleModel

home_blueprint = Blueprint("home_view", __name__)

@home_blueprint.route("/")
@home_blueprint.route("/home")
def home():
    return render_template("home.html", active = "home", admin_role = RoleModel.Admin.value, user_role = RoleModel.User.value)

src/views/like_view.py
from flask import Blueprint, redirect, url_for
from facades.user_facade import UserFacade
from facades.like_facade import LikeFacade
from models.client_error import ValidationError, AuthError

like_blueprint = Blueprint("like_view", __name__)

@like_blueprint.route("/vacations/like", methods = ['POST'])
def like_vacation():
    try:
        with UserFacade() as auth_facade:
            auth_facade.block_anonymous()

        with LikeFacade() as like_facade:
            like_facade.like_vacation()
        
        return redirect(url_for("vacations_view.vacations_list"))

    except ValidationError as err:
        return redirect(url_for("vacations_view.vacations_list", error = err.message))
    except AuthError as err:
        return redirect(url_for("auth_view.login", error = err.message))


@like_blueprint.route("/vacations/unlike", methods = ['POST'])
def unlike_vacation():
    try:
        with UserFacade() as auth_facade:
            auth_facade.block_anonymous()

        with LikeFacade() as like_facade:
            like_facade.unlike_vacation()
            
        return redirect(url_for("vacations_view.vacations_list"))
    
    except ValidationError as err:
        return redirect(url_for("vacations_view.vacations_list", error = err.message))
    except AuthError as err:
        return redirect(url_for("auth_view.login", error = err.message))
    

src/views/vacations_view.py
from flask import Blueprint, render_template, redirect, url_for, send_file, request, session
import json
from facades.vacation_facade import VacationFacade
from facades.user_facade import UserFacade
from facades.like_facade import LikeFacade
from models.client_error import ValidationError, AuthError, ResourceNotFound
from models.role_model import RoleModel
from utils.image_handler import ImageHandler

vacations_blueprint = Blueprint("vacations_view", __name__)

@vacations_blueprint.route("/vacations")
def vacations_list():
    try: 
        with UserFacade() as auth_facade:
            auth_facade.block_anonymous()

        error = request.args.get('error')

        with VacationFacade() as vacation_facade, LikeFacade() as like_facade:
            vacations = vacation_facade.return_all_vacations_ordered_by_start_date()
            countries = vacation_facade.return_all_countries()
            liked_vacation_amount = like_facade.get_liked_vacations_amount()
            users_and_their_liked_vacations = like_facade.get_users_and_their_liked_vacations(session["current_user"]['userId'])

        return render_template("vacations.html", active = "vacations", error = error, vacations = vacations, countries_dicts = countries, vacationLikeCount = liked_vacation_amount, usersLikedVacations = json.dumps(users_and_their_liked_vacations), admin_role = RoleModel.Admin.value, user_role = RoleModel.User.value)

    except AuthError as err:
        return redirect(url_for("auth_view.login", error = err.message))

@vacations_blueprint.route("/vacations/images/<string:image_name>")
def get_image(image_name):
    image_path = ImageHandler.get_image_path(image_name)
    return send_file(image_path)

@vacations_blueprint.route("/vacations/new", methods = ["GET", "POST"])
def add_vacation():
    try:
        with UserFacade() as auth_facade:
            auth_facade.block_non_admin()

        if request.method == "GET":
            error = request.args.get('error')
            with VacationFacade() as vacation_facade:
                countries = vacation_facade.return_all_countries()
            
            return render_template("insert_vacation.html", error = error, active = "insert", countries_dicts = countries, admin_role = RoleModel.Admin.value)
        
        with VacationFacade() as vacation_facade:
            vacation_facade.add_vacation()
        
        return redirect(url_for("vacations_view.vacations_list"))
    
    except AuthError as err:
        return redirect(url_for("auth_view.login", error = err.message))
    except ValidationError as err:
        return redirect(url_for("vacations_view.add_vacation", error = err.message))
        
@vacations_blueprint.route("/vacations/edit/<int:id>", methods = ["GET", "POST"])
def edit_vacation(id):
    try:
        with UserFacade() as auth_facade:
            auth_facade.block_non_admin()
        
        if request.method == "GET":
            error = request.args.get('error')
            with VacationFacade() as vacation_facade:
                requested_vacation = vacation_facade.return_one_vacation(id)
                countries = vacation_facade.return_all_countries()

            return render_template("edit_vacation.html", error = error , vacation = requested_vacation, countries_dicts = countries, admin_role = RoleModel.Admin.value)

        with VacationFacade() as vacation_facade:
            vacation_facade.update_vacation()
        
        return redirect(url_for("vacations_view.vacations_list"))
    
    except (AuthError, ResourceNotFound) as err:
        return redirect(url_for("vacations_view.vacations_list", error = err.message))
    except ValidationError as err:
        return redirect(url_for("vacations_view.edit_vacation", id = id, error = err.message))
    

@vacations_blueprint.route("/vacations/delete/<int:id>")
def delete_vacation(id):
    try:
        with UserFacade() as auth_facade:
            auth_facade.block_non_admin()
        
        with VacationFacade() as vacation_facade:
            vacation_facade.delete_vacation(id)
        return redirect(url_for("vacations_view.vacations_list"))
    
    except AuthError as err:
        return redirect(url_for("vacations_view.vacations_list", error = err.message))

    

src/templates/auth.html
{% set current_user = session.get("current_user") %}
    
{% if current_user %}
    <span>Hello {{current_user["firstName"]}} {{current_user["lastName"]}}</span>
    <span>|</span>
    <a href="{{url_for('auth_view.logout')}}">Logout</a>

{% else %}
    <span>Hello Guest</span>
    <span>|</span>
    <a href="{{url_for('auth_view.login')}}" {% if active == 'login' %} id = "active" class="activeCheck" {% endif %}>Login</a>
    <span>|</span>
    <a href="{{url_for('auth_view.register')}}" {% if active == 'register' %} id = "active" class="activeCheck" {% endif %}>Register</a>
{% endif %}

src/templates/edit_vacation.html
{% extends 'layout.html' %}


{% block title %} 
Edit vacation
{% endblock title %}


{% block content %}

<div class="insert-form-wrapper">
    <h1>Edit your vacation</h1>

    <form method="post"  enctype="multipart/form-data">
            <input type="hidden" value="{{vacation.vacationId}}" name="id"> 
            <label class="inputText">Country</label>
            <select id="ad" name="country_name" class="form-input" required>
            {% for country in countries_dicts %}
                {% if country["countryId"] == vacation.countryId %}
                    <option value='{{country["countryId"]}}' selected>{{country["countryName"]}}</option>

                {% else %}
                    <option value='{{country["countryId"]}}'>{{country["countryName"]}}</option>

                {% endif %}
            {% endfor %}
            </select>
            <br>
            <label class="inputText">Start date</label>
            <input type="date" value="{{vacation.vacationStartDate}}" name="start_date" class="form-input" required>
            <br>
            <label class="inputText">End date</label>
            <input type="date" value = "{{vacation.vacationEndDate}}" name="end_date" class="form-input" required>
            <br>
            <label class="inputText">Price</label>
            <input type="number" value="{{vacation.vacationPrice}}" name="price" class="form-input" min="0" max="10000" required>
            <br>
            <label class="inputText">Description</label>
            <textarea type="text" name="description" class="form-input" minlength="0" maxlength="800" cols="5" rows="5" required>{{vacation.vacationDescription}}</textarea>
            <br>
            <br>
            <label class="inputText">Image</label>
            <div class="image_container">
                <br>
                <img src="{{url_for('vacations_view.get_image', image_name = (vacation.photoFileName if vacation.photoFileName else '---'))}}" onclick="userClickedToChangeImage()" id="uploadFile" style="width: 300px; height: 300px;">
                <p class="overlay-text" onclick="userClickedToChangeImage()">Add image</p>
            </div>
            <input type="file" id="image_file" name="image" accept="image/*" onchange="loadFile(event)" style="display: none;">
            <br>
            
            <button class="customButton">Update</button>

    </form>
    <br>
    <br>
    <br>
    
</div>

{% endblock content %}

src/templates/home.html
{% extends 'layout.html' %}


{% block title %} 
Home
{% endblock title %}


{% block content %}

<div class="home-container">
    <div class="home-title-box">
        <h1 class="home-title-text">Hi! </h1>
        <h2 class="home-title-text">Thanks for checking in to EasyTour!</h2>
    </div>

    <div class="home-text-box">
        <div class="home-welcome-text">
            <p>Here you can find the best vacation deals around the globe!</p>
            <p>After registering and signing in - you can simply go to the <a class="vacationsLinkFromHome" href="{{url_for('vacations_view.vacations_list')}}">Vacations List</a> to see the best vacations around the planet.</p>            
            <p>Found an interesting tour?</p>
            <p>You can simply like your favorite ones!</p>
            <p class="large">Best tours.</p>
            <p class="dotted-line-larger">The easy way</p>
            <p>- EasyTour</p>


        </div>
    </div>
    
</div>



{% endblock content %}

src/templates/insert_vacation.html
{% extends 'layout.html' %}


{% block title %} 
Add vacation
{% endblock title %}


{% block content %}
<div class="insert-form-wrapper">
    <h1>Add another vacation here!</h1>

    <form method="post" enctype="multipart/form-data">
        <label class="inputText">Country</label>
        <select id="ad" name="country_name" class="form-input" required>
        {% for country in countries_dicts %}
        <option value='{{country["countryId"]}}'>{{country["countryName"]}}</option>
        {% endfor %}
        </select>
        <br>
        <label class="inputText">Start date</label>
        <input type="date" name="start_date" class="form-input" required>
        <br>
        <label class="inputText">End date</label>
        <input type="date" name="end_date" class="form-input" required>
        <br>
        <label class="inputText">Price</label>
        <input type="number" name="price" class="form-input" min="0" max="10000" required>
        <br>
        <label class="inputText">Description</label>
        <textarea type="text" name="description" class="form-input" minlength="0" maxlength="800" cols="5" rows="5" required></textarea>
        <br>
        <br>
        <label class="inputText">Image</label>
        <div class="image_container">
            <br>
            <img src="{{url_for('static', filename='images/vacation_images/no-image-icon-23485.png')}}" onclick="userClickedToChangeImage()" id="uploadFile" style="width: 300px; height: 300px;">
            <p class="overlay-text" onclick="userClickedToChangeImage()">Add image</p>
        </div>
        <input type="file" id="image_file" name="image" accept="image/*" onchange="loadFile(event)" style="display: none;">
        <br>
        <br>
        <button class="customButton">Add vacation</button>
        
    </form>
    <br>

</div>

{% endblock content %}

src/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='images/misc/favicon.ico') }}" />
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script defer src="{{url_for('static', filename='js/main.js')}}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <div class="layout">
        <header>
                {% include 'nav.html' %}
        </header>
        

        <main id="main">
            {% block content %}
            {% endblock content %}
        </main>

        <footer>
            <div>All rights reserved for the jonathan-david corporation LTD©</div>
        </footer>
    </div>

    {% if error %}<span class="error">{{error}}</span> {% endif %}
</body>
</html>

src/templates/login.html
{% extends 'layout.html' %}


{% block title %} 
login
{% endblock title %}


{% block content %}

<div class="login-form-wrapper">
    <h1>Login Here</h1>

    <form method="post">
        <label for="email" class="inputText" >Email</label>
        <div class="email-input-box">
            <input type="email" id="email" placeholder="example123@email.com" value="{{credentials.email if credentials.email else ''}}" name="email"  minlength="2" maxlength="100" required>
            <i class='bx bxs-user iconBox'></i>
        </div>
        <br>
        <label for="password" class="inputText">Password</label>
        <div class="password-input-box">
            <input type="password" id="password" name="password" minlength="5" maxlength="50" required>
            <i class='bx bxs-lock iconBox'></i>
        </div>
        <br>

        <button class="customButton">submit</button>
        
        <br>
        <div class="register-link-box">
            <span>Don't have an account yet?</span>
            <a class="loginLink" href="{{url_for('auth_view.register')}}">Register here</a>
        </div>
    </form>
</div>

{% endblock content %}

src/templates/nav.html
{% set current_user = session.get("current_user") %}

<div class="navigation-wrapper">
    <div class="navigation-options">
        <a href="{{url_for('home_view.home')}}"   {% if active == 'home' %} id = "active" {% endif %}>Home</a>
        {% if current_user["roleId"] == user_role or current_user["roleId"] == admin_role%}
        <a href="{{url_for('vacations_view.vacations_list')}}" {% if active == 'vacations' %} id = "active"  class="activeCheck" {% endif %}>Vacation list</a>
        {% endif %}
        {% if current_user["roleId"] == admin_role %}
        <a href="{{url_for('vacations_view.add_vacation')}}" {% if active == 'insert' %} id = "active" class="activeCheck" {% endif %}>Add vacation</a>
        {% endif %}
    </div>

    <div class="webName">
        <span>EasyTour</span>
    </div> 

    <div class="navigation-auth-options">
        {% include 'auth.html' %}
    </div>
</div>

src/templates/register.html
{% extends 'layout.html' %}


{% block title %} 
Register
{% endblock title %}


{% block content %}

<div class="form-registration-container">

    <div class="form-regestration-container">
        <div class="register-title"><h1>Register Here</h1></div>
    
        <div class="register-form">
            <form method="post" class="form-regestration">
                <label class="inputText" for="first_name">First Name</label>
                <input type="text" id="first_name" value="{{user.first_name if user.first_name else ''}}" name="first_name" class="form-input" minlength="2" maxlength="45"  required>
                <br>
                <label class="inputText" for="last_name">Last Name</label>
                <input type="text" id="last_name" value="{{user.last_name if user.last_name else ''}}" name="last_name" class="form-input" minlength="2" maxlength="45"  required>
                <br>
                <label class="inputText" for="email">Email</label>
                <input type="email" id="email" value="{{user.email if user.email else ''}}" name="email" class="form-input" minlength="2" maxlength="50" required>
                <br>
                <label class="inputText" for="password">Password</label>
                <input type="password" id="password" name="password" class="form-input" minlength="4" maxlength="100" required>
                <br>
                <button class="customButton">submit</button>
            </form>
            
            <div class="linkToLoginBox">
                <span>Already have an account?</span>
                
                <a class="loginLink" href="{{url_for('auth_view.login')}}">Login here</a>
            </div>
    
            <div class="globe"><p class="rotatingGlobe">A</p></div>
                
            
        </div>
        
    </div>

</div>
{% endblock content %}

src/templates/vacations.html
{% extends 'layout.html' %}


{% block title %} 
Vacations
{% endblock title %}


{% block content %}

{% set current_user = session.get("current_user") %}
{% if current_user["roleId"] != admin_role %}
    <div class="vacationOptionsContainer">
        <div class="vacationOptions card" style="width: 25rem;">
            <div class="card-body">
            <h5 class="card-title">See our amazing vacations!</h5>
            <p class="card-text">browse our dozens of amazing locations you can visit right now!</p>
            <br>
            <p class="card-text">How would you like to view your vacations?</p>
            <label>I want to see...</label>
            <br>
            <select onchange="changeVacationsView(this)" class="form-select" aria-label="Default select example">
                <option selected value="allVacations">All vacations</option>
                <option value="LikedVacations">My liked Vacations</option>
            </select>
            <label>Ordered by...</label>
            <br>
            <select onchange="changeVacationsOrder(this)" class="form-select" aria-label="Default select example">
                <option selected value="orderStartDate">Start date</option>
                <option value="orderPrice">Price</option>
                <option value="likedAmount">Amount of likes</option>
            </select>
            </div>
        </div>
    </div>


    <input type="hidden" value="{{vacationLikeCount}}" id="likeAmount">
    <input type="hidden", value="{{usersLikedVacations}}" id="userLikes">
{% endif %}

<div class="vacationGrid">
    {% for vacation in vacations %}
    {% set vacation_id = vacation.vacationId %}
    
    <div class="vacationCard" id="card{{vacation_id}}">
        <div class="image">
            <img src="{{url_for('vacations_view.get_image', image_name = (vacation.photoFileName if vacation.photoFileName else '---'))}}" class="vacationImage rounded-top">
            {% if current_user["roleId"] == admin_role %}
            <a href="{{url_for('vacations_view.edit_vacation', id = vacation.vacationId)}}">
                <button class="editVacation btn btn-primary rounded-pill">
                    <img src="{{url_for('static', filename='images/misc/edit.png')}}" width="16vw" height="16vh">
                    Edit
                </button>
            </a>

            <a href="{{url_for('vacations_view.delete_vacation', id = vacation.vacationId)}}">
                <button class="deleteVacation btn btn-primary rounded-pill" method onclick="confirmDelete()">
                    <img src="{{url_for('static', filename='images/misc/delete.png')}}" width="16vw" height="16vh">
                    Delete
                </button>
            </a>
            {% endif %}
            <p class="countryName">{{countries_dicts[vacation.countryId - 1]["countryName"]}}</p>
        </div>

        <div class="vacationDetailsAndLikes" id="detailsAndLikes{{vacation_id}}">
            <div class="vacationDetails">{{vacation.vacationStartDate}}<span class="vacationArrowSymbol">g</span> {{vacation.vacationEndDate}}</div>

            {% if current_user["roleId"] != admin_role %}
            <div class="vacationLikes">
                {# javascript syntax does'nt recognize jinja syntax and looks at {{variable}} as an error despite it working and getting the right variable #}
                <div class="heart" onclick="changeLikeStateAndSubmit({{vacation_id}})"></div>
                <span class="vacationLikeAmount{{vacation_id}}">0</span>
            </div>

            <form method="post" action="{{url_for('like_view.like_vacation')}}" class="hiddenLikeUnlikeInputForm"  id = "likeForm{{vacation_id}}">
                {# javascript syntax does'nt recognize jinja syntax and looks at {{variable}} as an error despite it working and getting the right variable #}
                <input type="submit" onclick="addLikeSubmit({{vacation_id}})" value="{{vacation_id}}" id="like{{vacation_id}}" class="hiddenLikeInputSubmit">
            </form>

            <form method="post" action="{{url_for('like_view.unlike_vacation')}}" class="hiddenLikeUnlikeInputForm"  id = "unLikeForm{{vacation_id}}">
                {# javascript syntax does'nt recognize jinja syntax and looks at {{variable}} as an error despite it working and getting the right variable #}
                <input type="submit" onclick="addUnlikeSubmit({{vacation_id}})" value="{{vacation_id}}" id="unlike{{vacation_id}}" class="hiddenUnlikeInputSubmit">
            </form>

            {% endif %}
        </div>

        <div class="vacationDescription" onclick="changeTextDisplay(this)">{{vacation.vacationDescription}}</div>
        <div class="vacationPrice"><div class="price btn btn-primary btn-lg">{{vacation.vacationPrice}}$</div></div>
    </div>
    {% endfor %}
</div>

{% endblock content %}